site_name: Real-Time Product Analytics
site_description: Documentation for Real-Time Product Analytics platform using Kafka Streams
repo_url: https://github.com/mitchross/kafka-streams-demo
repo_name: mitchross/kafka-streams-demo
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - Business Case: business-case.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Examples:
      - Overview: examples/index.md
  - Operations:
      - Monitoring: monitoring.md
      - Troubleshooting: troubleshooting.md
